system_prompt = "You are a helpful assistant."
general_schema = """You are a helpful assistant in evaluating the quality of the outputs for a given instruction along a given metric.
Your goal is to select the best output for the given metric. You will be presented with two outputs along with description of a metric and your task is to evaluate which output is better.
The two outputs are generated by two different AI assistants A and B respectively. Avoid any position biases and ensure that the order in which the responses were presented does not influence your decision. 
Do not allow the length of the responses to influence your evaluation. Do not favor certain names of the assistants.
Be as objective as possible. After providing your explanation, output your final verdict by strictly following this format: "[[A]]" if
assistant A is better, "[[B]]" if assistant B is better, "[[C]]" for a tie, and "[[D]]" if both the answers are unacceptable.
##Metric
{metric}
User Question]
{question}
[The Start of Assistant A's Answer]
{answer_a}
[The End of Assistant A's Answer]
[The Start of Assistant B's Answer]
{answer_b}
[The End of Assistant B's Answer]\n\n
{format_instruction}\n\n
"""

hallucination = """{
    "name": "hallucinations",
    "description": Hallucinations assess the extent to which a model's output remains anchored to, and consistent with, the input content provided.
        Text with hallucinations while linguistically fluent, are factually baseless or counterfactual in relation to the input. These hallucinations can
        manifest as additions, omissions, or distortions, and might lead to outputs that are misleading or factually incorrect. This metric serves as
        a check against unwarranted deviations from the ground truth provided in the input. Choose the answer that is factually correct and
        grounded in the input, do not choose the one that contains hallucinations or is factually incorrect.",

}

"""
task_quality = """{
    "name": "task_quality",
    "description": "Task Quality gauges the degree to which a model adheres to and executes the specific directives given in the prompt. This metric
        zeroes in exclusively on the fidelity of the model's response to the prompt's instructions. An ideal response not only recognizes the overt commands
        of the prompt but also respects its nuance and subtleties. Choose the response that follows the instructions more appropriately doing what is asked
        in the instruction and demonstrates higher task quality."
}
"""
content_quality = """{
    "name": "content_quality",
    "description": "Output Content Quality measures the overall caliber of the content generated, factoring in its relevance, clarity, originality,
        and linguistic fluency. High-quality output should not only be grammatically sound but should also convey information in an articulate, coherent,
        and engaging manner without any evidence of plagiarism, redundancy, or artificiality. This metric ensures that the produced content meets the
        expectations of originality, clarity, and contextual relevance in addition to linguistic fluency. Choose the resposnse that demostrates higher
        content quality by being more relevant, clear, original, and linguistically fluent.",

}
"""

reasoning_accuracy = """{

    "name": "reasoning_accuracy",
    "description": "Reasoning Accuracy assesses the extent to which the model's outputs are logically sound and mathematically correct.
       This metric focuses on the model's ability to apply logical reasoning, solve mathematical problems accurately, and present conclusions that are consistent with
       the principles of deductive and inductive reasoning. It is particularly crucial in tasks that require numerical calculations, data interpretation, or the application
       of mathematical formulas and algorithms. This metric is key in ensuring that outputs not only appear numerically or logically plausible but are factually and
       computationally correct. Choose the response that shows fully correct and logically sound reasoning and computations and demonstrates higher reasoning accuracy.",

}
"""