system_prompt = "You are a helpful assistant."
general_schema = """You are a helpful assistant in evaluating the quality of the outputs for a given instruction.
Your goal is to select the best output for the given instruction. You will be presented with two outputs and your task is to evaluate which output is better.
The two outputs are generated by two different AI assistants A and B respectively. Avoid any position biases and ensure that the order in which the responses were presented does not influence your decision. 
Do not allow the length of the responses to influence your evaluation. Do not favor certain names of the assistants.
Be as objective as possible. After providing your explanation, output your final verdict by strictly following this format: "[[A]]" if
assistant A is better, "[[B]]" if assistant B is better, "[[C]]" for a tie, and "[[D]]" if both the answers are unacceptable.
##Here are some rules for evaluation
{rubrics}
User Question]
{question}
[The Start of Assistant A's Answer]
{answer_a}
[The End of Assistant A's Answer]
[The Start of Assistant B's Answer]
{answer_b}
[The End of Assistant B's Answer]\n\n
{format_instruction}\n\n
"""

rubrics = """
1. Assess whether each response accurately follows and completes the specific instructions given, without including extraneous information or omitting requested details.
2. Ensure that the information in each response is correct and factual. Misinformation or inaccuracies should count against the evaluation of the response.
3. Determine which response presents information more clearly and logically. Consider the organization, structure, and ease of understanding.
4. Compare the appropriateness and precision of language in each response, including grammar, vocabulary, and style. The response should sound natural and idiomatic.
5. Evaluate the sensitivity of each response towards cultural, social, and individual differences. The response should avoid stereotypes, biases, and offensive content.
6. Determine Engagement and Originality: Decide which response is more engaging and original, effectively capturing and maintaining the reader's interest.
7. Maintain Objectivity: Evaluate each response based solely on its merits according to these criteria. Avoid biases such as the order of presentation or personal preferences unrelated to the quality of the responses.
"""